version: "3.7"

services:
  infraspeak-pie.api:
    build:
      args:
        user: api
        uid: 1000
      context: ./
      dockerfile: .docker/php/8-fpm/Dockerfile
    image: infraspeak-pie/api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - infraspeak-pie

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
      - infraspeak-pie

  infraspeak-pie.nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - infraspeak-pie

  infraspeak-pie.redis:
    image: redis:5.0.6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - infraspeak-pie

networks:
  infraspeak-pie:
    name: infraspeak-pie
