version: "3.7"

services:
  app:
    build:
      args:
        user: api
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    network_mode: "host"

  nginx:
    image: nginx:1.17-alpine
    container_name: api-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    network_mode: "host"

  infraspeak.redis:
    image: redis:5.0.6-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    network_mode: "host"


