version: "3.7"

services:
  infraspeak-pie.api:
    build:
      args:
        user: api
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - infraspeak-pie

  infraspeak-pie.nginx:
    image: nginx:1.17-alpine
    container_name: api-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - infraspeak-pie

  infraspeak-pie.redis:
    image: redis:5.0.6-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - infraspeak-pie

networks:
  infraspeak-pie:
    name: infraspeak-pie